version: "3"

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
    - "4444:4444"
    restart: always
 
  app:
    build:
      context: .
    image: josephcruisedocker8624/newsscape1
    volumes:
     - ./scape_data:/scape_data
    command: sh -c "python3 news_scape.py"
    depends_on:
     - selenium
